### ISSUE TITLE
Stream interface IndexError

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/sfx#10]
The following worked:
```python
st = StreamInterface("/reg/d/psdm/mfx/mfxlz0420/scratch/tmalla/optimize/lyzozyme/stream_files/lyzo-v1.stream") 
st.plot_peakogram()
```

But this one did not:
```python
st = StreamInterface("/reg/d/psdm/mfx/mfxlz0420/scratch/tmalla/optimize/clen-p2/stream_files/Geo-104.stream")
st.plot_peakogram()
```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_29822/1044716678.py in <module>
----> 1 st = StreamInterface("/reg/d/psdm/mfx/mfxlz0420/scratch/tmalla/optimize/clen-p2/stream_files/Geo-104.stream")
      2 st.plot_peakogram()

~/sfx_utils/sfx_utils/stream_interface.py in __init__(self, input_file, cell_only)
      9         self.stream_file = input_file
     10         self.cell_only = cell_only
---> 11         self.stream_data = self.read_stream(input_file)
     12 
     13     def read_stream(self, input_file):

~/sfx_utils/sfx_utils/stream_interface.py in read_stream(self, input_file)
     62         stream_data = np.array(stream_data)
     63         if not self.cell_only:
---> 64             stream_data[:,-1] = xtal_utils.compute_resolution(stream_data[:,2:8], stream_data[:,8:11])
     65 
     66         return stream_data

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by apeck12** [comment]
@fredericpoitevin, there only seem to be unindexed peaks in the Geo-104.stream file, hence why the `compute_resolution` call fails. Do you think we should have the `StreamInterface` class spit out a warning if it doesn't find any cells / reflections?

**Comment by fredericpoitevin** [comment]
oh that's weird, I thought this one had indexed peaks... I asked @73km on Slack.

But yes, in terms of behavior, I think it would help to catch this case and spit out a warning 👍

**Comment by 73km** [comment]
This had 2775 indexed peaks.

**Comment by apeck12** [comment]
@73km, could you point to which line numbers contain the indexed peaks? I thought indexed reflections were listed after the line "Reflections measured after indexing", but I don't see that line anywhere in the Geo-104.stream file.

**Comment by 73km** [comment]
They show up after "peaks from search". For indexed peaks there will be a line, few lines above, that says "indexed_by = {something}", for non indexed it will be "indexed_by = none"

**Comment by 73km** [comment]
@apeck12 Ah. Yes. I understand what you mean. For those geometry optimization runs, I skipped reflections to save computing time. Try "/reg/d/psdm/mfx/mfxlz0420/scratch/tmalla/indexing/v1/dark/stream_files/dark-v1.stream"

**Comment by apeck12** [comment]
In the case of no indexed reflections, the `StreamInterface` class can still be used to plot the unit cell distributions by setting `cell_only=True` during initialization.

The dark-v1.stream yields the following results:
![download-1](https://user-images.githubusercontent.com/6363287/155768751-cd6ba971-cf78-4698-965f-052a82397386.png)
![download-2](https://user-images.githubusercontent.com/6363287/155768755-4fbcef41-1829-4f7a-9edd-9ec6af0016d7.png)
