### ISSUE TITLE
Peakogram and reflection intensity

### ISSUE THREAD

**Issue by 73km** [lcls-users/sfx#8]
The wiki manual to get peakogram and reflection intensity doesn't produce the intended graph.  It only plots cell distribution. 

![image_2022-02-24_103729](https://user-images.githubusercontent.com/55704584/155586487-0a1bfae3-88f9-48e5-a24a-b646559910af.png)

**Comment by apeck12** [comment]
Thanks for catching this, @73km! The Wiki has been fixed.

**Comment by 73km** [comment]
![image_2022-02-24_112127](https://user-images.githubusercontent.com/55704584/155592608-42d853ee-65d6-429e-b56b-f7a45251f030.png)

@apeck12 There is another issue. See attached image.
